export const plans = [
    // {
    //   name: "Free",
    //   price: "0",
    //   originalPrice: "0",
    //   period: "forever",
    //   description: "Perfect for trying out the service",
    //   features: ["2 repo shares", "Basic link generation", "No expiration", "GitHub integration"],
    //   cta: "Try for free",
    //   popular: false,
    // },
    {
      name: "Pro",
      price: "4.99",
      originalPrice: "9.99",
      period: "one-time",
      description: "For serious developers small teams",
      features: [
        "20 GitHub repo shares",
        "Custom expiration dates",
        "Member limits",
        "Advanced analytics",
      ],
      cta: "Join Waitlist",
      popular: false,
    },
    {
      name: "Power User",
      price: "9.99",
      originalPrice: "19.99",
      period: "one-time",
      description: "For power users and development teams",
      features: [
        "Everything in Pro",
        "Unlimited GitHub repo shares",
        "Bucket sharing",
        "More features coming soon",
      ],
      cta: "Join Waitlist",
      popular: false,
    },
]