export const plans = [
    {
      name: "Free",
      price: "0",
      period: "forever",
      description: "Perfect for trying out the service",
      features: ["2 repo shares", "Basic link generation", "No expiration", "GitHub integration"],
      cta: "Try for free",
      popular: false,
    },
    {
      name: "Pro",
      price: "9.99",
      period: "one-time",
      description: "For serious developers small teams",
      features: [
        "20 repo shares",
        "Custom expiration dates",
        "Member limits",
        "Advanced analytics",
        "GitHub integration",
      ],
      cta: "Buy Now",
      popular: false,
    },
    {
      name: "Power User",
      price: "19.99",
      period: "one-time",
      description: "Advanced features for power users and development teams",
      features: [
        "Everything in Pro",
        "Unlimited repo shares",
        "Bucket sharing",
        "More features coming soon",
      ],
      cta: "Buy Now",
      popular: false,
    },
]